### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by milesj** [z-jxy/rpkl#10]
Hello,

I'm very excited about pkl as a configuration format, and would like to support `.pkl` files in [moon](https://moonrepo.dev/moon). 

Most Rust crates around pkl seem abandoned except for this one, so I'm curious what the state of this crate is and if it's ready enough to start using it?

Thanks!

**Comment by z-jxy** [comment]
Currently, I think the only thing missing is evaluating non primitive types within lists (you can have a `List<String>`, but not `List<Bird>`). I haven't gotten around to implementing this yet, but planning to add support for it within the next couple days.

Once that's implemented, aside from the codegen feature of the crate, I would say its ready for use

**Comment by z-jxy** [comment]
> you can have a `List<String>`, but not `List<Bird>`.

This is now implemented under the `non-primitive-lists` branch. Just working on some tests before merging for next release

**Comment by milesj** [comment]
Awesome stuff! 🙏
