### ISSUE TITLE
How to handle enum values?

### ISSUE THREAD

**Issue by milesj** [z-jxy/rpkl#16]
@z-jxy 

Me again. Ran into another issue, this time around enums.

So I make use of enums heavily, primarily through serde of course. Here's an example: https://github.com/moonrepo/moon/blob/master/crates/config/src/workspace/codeowners_config.rs#L8

In YAML, configuring this is easy:

```yml
codeowners:
  orderBy: 'project-name'
```

But in Pkl, I can't seem to figure out how to write this? All of these don't work.

A string errors with "invalid type: string "project-name", expected enum CodeownersOrderBy".

```pkl
codeowners {
  orderBy = "project-name"
  // OR
  orderBy = "ProjectName"
}
```

If I try to emulate it, it fails to parse.

```pkl
codeowners {
  orderBy = CodeownersOrderBy::ProjectName
  // OR
  orderBy = ProjectName
}
```

Is this a situation where I'll need to create a scheme/lib that users can import from? It would be nice if I could piggyback off serde here like YAML does.

**Comment by z-jxy** [comment]
Pretty sure this is an issue where the enum deserializer isn't getting triggered, similar to the [issue with optional values](https://github.com/z-jxy/rpkl/issues/12#issue-2433195512). I should be able to get this working

One way to do this in pkl would be to have a module with a [union](https://pkl-lang.org/main/current/language-reference/index.html#union-types) field that users amend to

```pkl
typealias CodeownersOrderBy = "ProjectName"|"FileSource"

// then in your class
orderBy: CodeownersOrderBy

// OR

orderBy: "ProjectName"|*"FileSource" // '*' prefix makes it the default value
```

**Comment by z-jxy** [comment]
Got the implementation for enums working and added an example. Lmk if you run into any other issues with it
