### ISSUE TITLE
allowedResources = null disallows reading env variables

### ISSUE THREAD

**Issue by harlequin** [z-jxy/rpkl#21]
The current crate is calling the pkl server with following configuration

```
[pkl-server] Received message: CreateEvaluatorRequest(requestId=135, allowedModules=[pkl:, repl:, file:, customfs:], allowedResources=null, clientModuleReaders=[ModuleReaderSpec[scheme=customfs, hasHierarchicalUris=true, isLocal=true, isGlobbable=true]], clientResourceReaders=null, modulePaths=null, env=null, properties=null, timeout=null, rootDir=null, cacheDir=null, outputFormat=null, project=null, http=null, externalModuleReaders=null, externalResourceReaders=null)
```

The setting `allowedResources` controls which the access to resources.

The [cli](https://pkl-lang.org/main/current/pkl-cli/index.html) interface defines here a default list

```
env:,prop:,package:,projectpackage:
```

It would be great that your crate also supports, at least, the default configurations which a pair to the cli from pkl.

**Comment by z-jxy** [comment]
Working on this now. I've implemented support for reading the environment variables, but properties will require being able to pass values to the evaluator; I'm thinking I'll expose this through a separate function `from_config_with_options`, and the original `from_config` function will just call into it.

**Comment by harlequin** [comment]
Sounds straight forward.
Maybe as default you can use the same as from the cli

**Comment by z-jxy** [comment]
`env:,prop:,package:,projectpackage:` are now added to the allowed resources
